CREATE TABLE [dbo].[LOCAL]
(
[ID_LOCAL] [int] NOT NULL,
[NOME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COD_POSTAL] [int] NULL,
[MORADA] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LATITUDE] [real] NULL,
[LONGITUDE] [real] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOCAL] ADD CONSTRAINT [PK_LOCAL] PRIMARY KEY NONCLUSTERED  ([ID_LOCAL]) ON [PRIMARY]
GO
