CREATE TABLE [dbo].[ORCAMENTOS]
(
[ID] [int] NOT NULL,
[NIF] [int] NULL,
[PRECO] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORCAMENTOS] ADD CONSTRAINT [PK_ORCAMENTOS] PRIMARY KEY NONCLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PEDIDO_FK] ON [dbo].[ORCAMENTOS] ([NIF]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORCAMENTOS] ADD CONSTRAINT [FK_ORCAMENT_PEDIDO_CLIENTES] FOREIGN KEY ([NIF]) REFERENCES [dbo].[CLIENTES] ([NIF])
GO
