CREATE TABLE [dbo].[FORNECEDOR]
(
[ID_FORNECEDOR] [int] NOT NULL,
[NOME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MORADA] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NIF] [numeric] (9, 0) NOT NULL,
[TELEFONE] [numeric] (15, 0) NULL,
[TELEMOVEL] [numeric] (15, 0) NULL,
[EMAIL] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FORNECEDOR] ADD CONSTRAINT [PK_FORNECEDOR] PRIMARY KEY NONCLUSTERED  ([ID_FORNECEDOR]) ON [PRIMARY]
GO
