CREATE TABLE [dbo].[PRODUTO]
(
[ID_PRODUTO] [int] NOT NULL,
[ID_CATEGORIA] [int] NULL,
[NOME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DESCRICAO] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUTO] ADD CONSTRAINT [PK_PRODUTO] PRIMARY KEY NONCLUSTERED  ([ID_PRODUTO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [TEM_CATEGORIA_FK] ON [dbo].[PRODUTO] ([ID_CATEGORIA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUTO] ADD CONSTRAINT [FK_PRODUTO_TEM_CATEG_CATEGORI] FOREIGN KEY ([ID_CATEGORIA]) REFERENCES [dbo].[CATEGORIA] ([ID_CATEGORIA])
GO
