CREATE TABLE [dbo].[PEDIDO]
(
[ID_PEDIDO] [int] NOT NULL,
[ID_CLIENTE] [int] NOT NULL,
[ID_LOCAL] [int] NOT NULL,
[NOME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATA_CRIACAO] [datetime] NOT NULL,
[NUM_PESSOAS] [int] NULL,
[DATA_EVENTO] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIDO] ADD CONSTRAINT [PK_PEDIDO] PRIMARY KEY NONCLUSTERED  ([ID_PEDIDO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [EFECTUA_FK] ON [dbo].[PEDIDO] ([ID_CLIENTE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [REALIZA_SE_NUM_LOCAL_FK] ON [dbo].[PEDIDO] ([ID_LOCAL]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIDO] ADD CONSTRAINT [FK_PEDIDO_EFECTUA_CLIENTE] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [dbo].[CLIENTE] ([ID_CLIENTE])
GO
ALTER TABLE [dbo].[PEDIDO] ADD CONSTRAINT [FK_PEDIDO_REALIZA_S_LOCAL] FOREIGN KEY ([ID_LOCAL]) REFERENCES [dbo].[LOCAL] ([ID_LOCAL])
GO
