CREATE TABLE [dbo].[LINHA_PEDIDO]
(
[ID_PEDIDO] [int] NOT NULL,
[ID_LINHA_PEDIDO] [int] NOT NULL,
[ID_PRODUTO] [int] NOT NULL,
[QTD_PRODUTO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LINHA_PEDIDO] ADD CONSTRAINT [PK_LINHA_PEDIDO] PRIMARY KEY NONCLUSTERED  ([ID_PEDIDO], [ID_LINHA_PEDIDO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PEDIDO_TEM_LINHAS_FK] ON [dbo].[LINHA_PEDIDO] ([ID_PEDIDO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PEDIDO_CONTEM_PRODUTO_FK] ON [dbo].[LINHA_PEDIDO] ([ID_PRODUTO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LINHA_PEDIDO] ADD CONSTRAINT [FK_LINHA_PE_PEDIDO_CO_PRODUTO] FOREIGN KEY ([ID_PRODUTO]) REFERENCES [dbo].[PRODUTO] ([ID_PRODUTO])
GO
ALTER TABLE [dbo].[LINHA_PEDIDO] ADD CONSTRAINT [FK_LINHA_PE_PEDIDO_TE_PEDIDO] FOREIGN KEY ([ID_PEDIDO]) REFERENCES [dbo].[PEDIDO] ([ID_PEDIDO])
GO
