CREATE TABLE [dbo].[PRODUTOS]
(
[ID_PRODUTO] [int] NOT NULL,
[ID] [int] NULL,
[TIPO] [char] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOME] [char] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUTOS] ADD CONSTRAINT [PK_PRODUTOS] PRIMARY KEY NONCLUSTERED  ([ID_PRODUTO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [EMENTA_FK] ON [dbo].[PRODUTOS] ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUTOS] ADD CONSTRAINT [FK_PRODUTOS_EMENTA_ORCAMENT] FOREIGN KEY ([ID]) REFERENCES [dbo].[ORCAMENTOS] ([ID])
GO
