CREATE TABLE [dbo].[AVALIACAO]
(
[ID_AVALIACAO] [int] NOT NULL,
[ID_FORNECEDOR] [int] NOT NULL,
[GLOBAL] [int] NOT NULL,
[COMUNICACAO] [int] NOT NULL,
[PRECO] [int] NOT NULL,
[SERVICO] [int] NOT NULL,
[SIMPATIA] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AVALIACAO] ADD CONSTRAINT [PK_AVALIACAO] PRIMARY KEY NONCLUSTERED  ([ID_AVALIACAO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [AVALIADO_FK] ON [dbo].[AVALIACAO] ([ID_FORNECEDOR]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AVALIACAO] ADD CONSTRAINT [FK_AVALIACA_AVALIADO_FORNECED] FOREIGN KEY ([ID_FORNECEDOR]) REFERENCES [dbo].[FORNECEDOR] ([ID_FORNECEDOR])
GO
